export const schemaHints = {
  termToTables: {
    "הון עצמי": ["funds_overview.own_equity"],
    "סכום זמין": ["funds_overview.available_funds"],
    "קרן": ["funds_overview.fund_principal", "funds.balance"],
    "הלוואה": ["loans.loan_amount", "loans.remaining_balance"],
    "הלוואות": ["loans.loan_amount", "loans.remaining_balance"],
    "תרומה": ["donations.amount", "funds_overview.total_donations"],
    "תרומות": ["donations.amount", "funds_overview.total_donations"],
    "הפקדה": ["deposits.current_balance", "monthly_deposits.amount"],
    "הפקדות": ["deposits", "monthly_deposits.amount"],
    "יתרה": ["loans.remaining_balance", "deposits.current_balance", "payment_details.monthly_balance"],
    "השקעה": ["investments.current_value", "investments.total_principal_invested"],
    "השקעות": ["investments.current_value", "investments.total_principal_invested"],
    "הוצאות": ["expenses.amount", "funds_overview.total_expenses"],
    "בנק": ["bank_current.amount"],
    "משתמש": ["users.first_name", "users.last_name", "users.join_date"],
    "משתמשים": ["users.first_name", "users.last_name", "users.join_date"],
  },
  tables: {
    bank_current: {
      columns: ["id", "bank_name", "date", "amount"],
      dateColumns: ["date"],
      amountColumns: ["amount"],
    },
    cash_holdings: {
      columns: ["id", "amount", "note", "is_active"],
      dateColumns: [],
      amountColumns: ["amount"],
    },
    deposits: {
      columns: ["id", "start_date", "end_date", "initialDeposit", "current_balance", "isActive"],
      dateColumns: ["start_date", "end_date"],
      amountColumns: ["initialDeposit", "current_balance"],
    },
    donations: {
      columns: ["id", "date", "action", "amount", "donation_reason"],
      dateColumns: ["date"],
      amountColumns: ["amount"],
    },
    expenses: {
      columns: ["id", "amount", "expenseDate"],
      dateColumns: ["expenseDate"],
      amountColumns: ["amount"],
    },
    expenses_category: {
      columns: ["id", "name"],
      dateColumns: [],
      amountColumns: [],
    },
    funds: {
      columns: ["id", "name", "balance"],
      dateColumns: [],
      amountColumns: ["balance"],
    },
    fund_year_stats: {
      columns: ["id", "year", "fundId", "donatedTotal", "withdrawnTotal"],
      dateColumns: ["year"],
      amountColumns: ["donatedTotal", "withdrawnTotal"],
    },
    funds_overview: {
      columns: [
        "id",
        "own_equity",
        "fund_principal",
        "total_loaned_out",
        "total_invested",
        "Investment_profits",
        "special_funds",
        "monthly_deposits",
        "total_donations",
        "total_equity_donations",
        "available_funds",
        "cash_holdings",
        "total_user_deposits",
        "total_expenses",
        "standing_order_return",
        "fund_details",
      ],
      dateColumns: [],
      amountColumns: [
        "own_equity",
        "fund_principal",
        "total_loaned_out",
        "total_invested",
        "Investment_profits",
        "special_funds",
        "monthly_deposits",
        "total_donations",
        "total_equity_donations",
        "available_funds",
        "cash_holdings",
        "total_user_deposits",
        "total_expenses",
        "standing_order_return",
      ],
    },
    funds_overview_by_year: {
      columns: [
        "id",
        "year",
        "total_monthly_deposits",
        "total_equity_donations",
        "special_fund_donations",
        "total_special_funds_withdrawn",
        "total_loans_taken",
        "total_loans_amount",
        "total_loans_repaid",
        "total_fixed_deposits_added",
        "total_fixed_deposits_withdrawn",
        "total_standing_order_return",
        "total_investments_out",
        "total_investments_in",
        "fund_details_donated",
        "fund_details_withdrawn",
        "total_expenses",
        "total_donations",
      ],
      dateColumns: ["year"],
      amountColumns: [
        "total_monthly_deposits",
        "total_equity_donations",
        "special_fund_donations",
        "total_special_funds_withdrawn",
        "total_loans_taken",
        "total_loans_amount",
        "total_loans_repaid",
        "total_fixed_deposits_added",
        "total_fixed_deposits_withdrawn",
        "total_standing_order_return",
        "total_investments_out",
        "total_investments_in",
        "total_expenses",
        "total_donations",
      ],
    },
    investments: {
      columns: [
        "id",
        "investment_name",
        "investment_by",
        "company_name",
        "investment_portfolio_number",
        "total_principal_invested",
        "current_value",
        "principal_remaining",
        "profit_realized",
        "withdrawn_total",
        "management_fees_total",
        "start_date",
        "last_update",
        "is_active",
      ],
      dateColumns: ["start_date", "last_update"],
      amountColumns: [
        "total_principal_invested",
        "current_value",
        "principal_remaining",
        "profit_realized",
        "withdrawn_total",
        "management_fees_total",
      ],
    },
    investment_transactions: {
      columns: ["id", "transaction_type", "amount", "transaction_date", "note"],
      dateColumns: ["transaction_date"],
      amountColumns: ["amount"],
    },
    loans: {
      columns: [
        "id",
        "initial_loan_amount",
        "loan_amount",
        "loan_date",
        "purpose",
        "monthly_payment",
        "payment_date",
        "isActive",
        "remaining_balance",
        "total_installments",
        "total_remaining_payments",
        "initial_monthly_payment",
        "first_payment_date",
        "balance",
        "guarantor1",
        "guarantor2",
      ],
      dateColumns: ["loan_date", "first_payment_date"],
      amountColumns: [
        "initial_loan_amount",
        "loan_amount",
        "monthly_payment",
        "remaining_balance",
        "total_installments",
        "total_remaining_payments",
        "initial_monthly_payment",
        "balance",
      ],
    },
    loan_actions: {
      columns: ["id", "action_type", "date", "value"],
      dateColumns: ["date"],
      amountColumns: ["value"],
    },
    membership_roles: {
      columns: ["id", "name"],
      dateColumns: [],
      amountColumns: [],
    },
    monthly_deposits: {
      columns: ["id", "deposit_date", "payment_method", "amount", "month", "year"],
      dateColumns: ["deposit_date"],
      amountColumns: ["amount"],
    },
    order_return: {
      columns: ["id", "date", "amount", "paid", "paid_at", "note"],
      dateColumns: ["date", "paid_at"],
      amountColumns: ["amount"],
    },
    payment_details: {
      columns: [
        "id",
        "bank_number",
        "bank_branch",
        "bank_account_number",
        "charge_date",
        "payment_method",
        "monthly_balance",
        "loan_balances",
      ],
      dateColumns: ["charge_date"],
      amountColumns: ["monthly_balance"],
    },
    requests: {
      columns: ["id", "requestDate", "request", "status"],
      dateColumns: ["requestDate"],
      amountColumns: [],
    },
    role_monthly_rates: {
      columns: ["id", "amount"],
      dateColumns: [],
      amountColumns: ["amount"],
    },
    user_financial_by_year: {
      columns: [
        "id",
        "year",
        "total_monthly_deposits",
        "total_equity_donations",
        "special_fund_donations",
        "total_loans_taken",
        "total_loans_repaid",
        "total_fixed_deposits_added",
        "total_fixed_deposits_withdrawn",
        "total_standing_order_return",
      ],
      dateColumns: ["year"],
      amountColumns: [
        "total_monthly_deposits",
        "total_equity_donations",
        "special_fund_donations",
        "total_loans_taken",
        "total_loans_repaid",
        "total_fixed_deposits_added",
        "total_fixed_deposits_withdrawn",
        "total_standing_order_return",
      ],
    },
    "user-financials": {
      columns: [
        "id",
        "total_donations",
        "total_monthly_deposits",
        "total_equity_donations",
        "total_cash_holdings",
        "total_special_fund_donations",
        "total_loans_taken",
        "total_loans_repaid",
        "total_fixed_deposits_deposited",
        "total_fixed_deposits_withdrawn",
        "total_standing_order_return",
      ],
      dateColumns: [],
      amountColumns: [
        "total_donations",
        "total_monthly_deposits",
        "total_equity_donations",
        "total_cash_holdings",
        "total_special_fund_donations",
        "total_loans_taken",
        "total_loans_repaid",
        "total_fixed_deposits_deposited",
        "total_fixed_deposits_withdrawn",
        "total_standing_order_return",
      ],
    },
    user_role_history: {
      columns: ["id"],
      dateColumns: [],
      amountColumns: [],
    },
    users: {
      columns: [
        "id",
        "first_name",
        "last_name",
        "id_number",
        "email_address",
        "phone_number",
        "is_member",
        "spouse_first_name",
        "spouse_last_name",
        "spouse_id_number",
        "notify_account",
        "notify_receipts",
        "notify_general",
        "is_admin",
        "membership_type",
        "join_date",
      ],
      dateColumns: ["join_date"],
      amountColumns: [],
    },
  },
};
