export enum TransactionType {
    INITIAL_INVESTMENT = 'INITIAL_INVESTMENT',
    ADDITIONAL_INVESTMENT = 'ADDITIONAL_INVESTMENT',
    VALUE_UPDATE = 'VALUE_UPDATE',
    WITHDRAWAL = 'WITHDRAWAL',
    MANAGEMENT_FEE = 'MANAGEMENT_FEE',
  }
  